TOTAL_MUTATIONS:
  MIN_MUTATIONS_PER_CLASS: 30
  MIN_MUTATIONS_PER_METHOD: 5
  MIN_MUTATIONS_PER_INSTRUCTION: 0.5
ENABLE_MUTATORS:
  CONDTIONALS_BOUNDARY: true
  INCREMENTS: true
  INVERT_NEGS: true
  MATH: true
  NEGATE_CONDITIONALS: true
  RETURN_VALS: true
  VOID_METHOD_CALLS: false
  AOR:
